test:
  user:
    age: 67a
  comm: 3ttt
spring:
  cloud:
    gateway:
      routes:
        - id: route11
          uri: http://example1.org
          predicates:
            - Path=/example1/**
          filters:
            - AddRequestHeader=X-Example, Value  
