spring:
  cloud:
    config:
      server:
        prefix: /scc
        jdbc:
          enabled: true
          sql: SELECT P_KEY, VALUE FROM  PROPERTIES  where APPLICATION=? and PROFILE=? and LABEL=?
#        git:
#          default-label: main
#          uri: https://github.com/joomn11/spring-boot-admin-repo.git
    kubernetes:
      discovery:
        service-labels:
          type: spring-boot
  boot:
    admin:
      context-path: /sba
      monitor:
        status-interval: 3s
        status-lifetime: 3s
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://master-db:3306/SBA
    username: root
    password: root