apiVersion: v1
kind: Service
metadata:
  namespace: ttt-aa
  name: admin-service
  labels:
    type: spring-boot
spec:
  type: NodePort
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
  selector:
    app: admin
