apiVersion: v1
kind: ConfigMap
metadata:
        name: mysql-config
data:
        myopt.cnf: |
                [mysqld]
                bind-address=0.0.0.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: master-db
spec:
    selector:
        matchLabels:
            run: master-db
    template:
        metadata:
            labels:
                run: master-db
        spec:
            volumes:
                - name: config-volume
                  configMap:
                      name: mysql-config
                      optional: true
            containers:
                - name: mariadb
                  image: mariadb:10.4
                  env:
                      - name: TZ
                        value: "Asia/Seoul"
                      - name: MYSQL_ROOT_PASSWORD
                        value: "root"
                      - name: character-set-server
                        value: "utf8mb4"
                      - name: collation-server
                        value: "utf8mb4_unicode_ci"
                  ports:
                      - containerPort: 3306
                  volumeMounts:
                      - name: config-volume
                        mountPath: /etc/mysql/mariadb.conf.d
---
apiVersion: v1
kind: Service
metadata:
    name: master-db
spec:
    type: NodePort
    ports:
        - port: 3306
          protocol: TCP
          targetPort: 3306
    selector:
        run: master-db
        
