server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
spring:
  application:
    name: apptest
  profiles:
    active:
    - dev,test
  config:
    import:
    - optional:configserver:http://admin-service:8080/scc
  jmx:
    enabled: true
  boot:
    admin:
      client:
        instance:
          metadata:
            tags:
              environment: "tag-test1"
info:
  tags:
    environment: "tag-test1"
                  
logging:
  file:
    name: "/var/log/sample-boot-application.log"    
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
