kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: ttt-aa
  name: admin
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]
